### ISSUE TITLE
Aeon Purifier - (Tactical Missile Launcher) - Does no damage

### ISSUE THREAD

**Issue by Cyrris** [Uveso/BlackOpsFAF-Unleashed#1]
I know this worked fine last year, so I believe this may be due to more recent changes in FAF.

To replicate, simply build a T3 Aeon tac missile launcher and fire at ground targets. No damage is dealt to the targets. It does appear to do damage to shields on the way down though, just nothing actually on the ground.

I am wondering if it is related to [what I saw in the base game back in April](https://github.com/FAForever/fa/issues/3802), and if BlackOps might need some tweaks for compatibility there. Honestly not sure if I am reporting this in the right place - if it should be on FAF itself or just the mod.

Zip file containing log and replay: [game_17141043.zip](https://github.com/Uveso/BlackOpsFAF-Unleashed/files/8812125/game_17141043.zip)

Gametime:
27:20 - I launch T3 tac missiles at shields, shields appear to fall
28:20 - I launch at unshielded buildings
28:52 - Launched missiles land on buildings, no damage observed

Nothing relevant is seen in the log file at these times.

**Comment by Uveso** [comment]
@Cyrris ,

yes you can reports bugs here or in the forum:
https://forum.faforever.com/topic/353/

Thanks for reporting!

**Comment by Uveso** [comment]
issue fixed in version v20
