### ISSUE TITLE
BlackOpsFAF-Unleashed conflict with BrewLAN Penetration module.

### ISSUE THREAD

**Issue by Wolski2000** [Uveso/BlackOpsFAF-Unleashed#6]
After testing the new version of BlackOps I came across this bug. The game works fine with (I think) all BrewLAN modules except Penetration.

Log file provided below.
[game_19875176.log](https://github.com/Uveso/BlackOpsFAF-Unleashed/files/11380946/game_19875176.log)

**Comment by Uveso** [comment]
Hello @Wolski2000 

you did not reply to the last fix we did 8 hours ago:
https://github.com/The-Balthazar/BrewLAN/issues/40

Is this the same issue or a new error?
i viewed the log and looks like its a different error.
Can you confirm this?

**Comment by Wolski2000** [comment]
BrewLAN with all it's modules, except penetration, worked fine after that last patch.
This error is a new one. Haven't tested BlackOps Unleashed with any BrewLAN modules earlier since it wasn't working with the base BrewLAN.

**Comment by Uveso** [comment]
Thanks for your response!

Baltazar was once again kind enough to provide a solution to this problem.
https://github.com/Uveso/BlackOpsFAF-Unleashed/pull/7

i will update & upload this today or sunday.
